language: cpp
sudo: required
dist: trusty
services:
  - docker
python:
  - "2.7"
compiler:
- gcc
os:
- linux
env:
  global:

before_install:
- echo $LANG
- echo $LC_ALL
# - test -n $CC && unset CC

before_script:

install:

script:
- docker build -f Dockerfile -t $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER .

branches:
  only:
  - master
  - "/^v\\d+\\./"

notifications:
  email:
  - allixender@googlemail.com
